/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Karol Miklas (https://sketchfab.com/karolmiklas)
license: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
source: https://sketchfab.com/3d-models/free-merc-hovercar-oFfjKlslHqXgtKdKqEtpffmSv6h
title: (FREE) Merc Hovercar
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import useKeyboard from "../hooks/useKeyboardControls";
import { Vector3 } from "three";

export function Car(props) {
  const { nodes, materials } = useGLTF("/assets/free_merc_hovercar.glb");
  const ref = useRef();
  const { forward, backward, left, right, shift } = useKeyboard();

  useFrame(() => {
    if (forward) {
      ref.current.translateZ(0.02);
    } else if (backward) {
      ref.current.translateZ(-0.02);
    } else if (left) {
      if (shift) {
        ref.current.rotateOnAxis(new Vector3(0, 1, 0), (Math.PI / 2) * 0.02);
      }
      ref.current.translateX(0.02);
    } else if (right) {
      if (shift) {
        ref.current.rotateOnAxis(new Vector3(0, 1, 0), (Math.PI / 2) * -0.02);
      }
      ref.current.translateX(-0.02);
    }
  });

  return (
    <group {...props} dispose={null} ref={ref}>
      <group
        position={[0.02, -0.07, -0.05]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.5}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_0.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_1.geometry}
          material={materials.Material_light}
        />
        <group position={[0, 0, -0.58]} scale={[1.19, 2, 1]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_0.geometry}
            material={materials.Plane_0}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/assets/free_merc_hovercar.glb");
